// flow-typed signature: 823b1b16f425e90edf1ced4236952256
// flow-typed version: <<STUB>>/auto-bind_v^2.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auto-bind'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'auto-bind' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'auto-bind/index' {
  declare module.exports: $Exports<'auto-bind'>;
}
declare module 'auto-bind/index.js' {
  declare module.exports: $Exports<'auto-bind'>;
}
