// flow-typed signature: b81b597514694291b8a4ae1ffa7ab608
// flow-typed version: <<STUB>>/react-isolated-scroll_v^0.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-isolated-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-isolated-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-isolated-scroll/demo/index' {
  declare module.exports: any;
}

declare module 'react-isolated-scroll/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'react-isolated-scroll/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-isolated-scroll/demo/index.js' {
  declare module.exports: $Exports<'react-isolated-scroll/demo/index'>;
}
declare module 'react-isolated-scroll/demo/webpack.config.js' {
  declare module.exports: $Exports<'react-isolated-scroll/demo/webpack.config'>;
}
declare module 'react-isolated-scroll/lib/index.js' {
  declare module.exports: $Exports<'react-isolated-scroll/lib/index'>;
}
