// flow-typed signature: d059a2cb2764cc942a1f8d79982fbaef
// flow-typed version: <<STUB>>/xml-parser_v^1.2.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xml-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xml-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'xml-parser/index' {
  declare module.exports: $Exports<'xml-parser'>;
}
declare module 'xml-parser/index.js' {
  declare module.exports: $Exports<'xml-parser'>;
}
