// flow-typed signature: 09525e872479d5a3d3c29a5be30b6ee2
// flow-typed version: <<STUB>>/react-adal_v^0.4.19/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-adal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-adal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-adal/lib/adal' {
  declare module.exports: any;
}

declare module 'react-adal/lib/react-adal' {
  declare module.exports: any;
}

declare module 'react-adal/sample/adalConfig' {
  declare module.exports: any;
}

declare module 'react-adal/sample/index' {
  declare module.exports: any;
}

declare module 'react-adal/src/adal' {
  declare module.exports: any;
}

declare module 'react-adal/src/react-adal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-adal/lib/adal.js' {
  declare module.exports: $Exports<'react-adal/lib/adal'>;
}
declare module 'react-adal/lib/react-adal.js' {
  declare module.exports: $Exports<'react-adal/lib/react-adal'>;
}
declare module 'react-adal/sample/adalConfig.js' {
  declare module.exports: $Exports<'react-adal/sample/adalConfig'>;
}
declare module 'react-adal/sample/index.js' {
  declare module.exports: $Exports<'react-adal/sample/index'>;
}
declare module 'react-adal/src/adal.js' {
  declare module.exports: $Exports<'react-adal/src/adal'>;
}
declare module 'react-adal/src/react-adal.js' {
  declare module.exports: $Exports<'react-adal/src/react-adal'>;
}
